### ISSUE TITLE
Last question please

### ISSUE THREAD

**Issue by ThreadShakur** [DrBomb/python-steamcommunity#10]
When i call func GetTradeOffers i got {u'response': {}}

my arguments is:
                'get_sent_offers':int(kwargs.get('get_sent_offers',0)),
                'get_received_offers':int(kwargs.get('get_received_offers',1)),
                'get_descriptions':int(kwargs.get('get_descriptions',0)),
                'active_only':int(kwargs.get('active_only',1)),
                'historical_only':int(kwargs.get('historical_only',0)),

i have 15 received offers in steam, but got a empty response

**Comment by DrBomb** [comment]
Use this page to check your request: https://lab.xpaw.me/steam_api_documentation.html#IEconService

If you find any bugs you're welcome to submit an issue
