### ISSUE TITLE
Bug with GetTradeConformations in SteamLogin

### ISSUE THREAD

**Issue by ThreadShakur** [DrBomb/python-steamcommunity#12]
I have error

`Invalid authenticator It looks like your Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes. This could be caused by an inaccurate clock or bad timezone settings on your device. If your time settings are correct, it could be that a different device has been set up to provide the Steam Guard codes for your account, which means the authenticator on this device is no longer valid.`

Maybe problem in request?

**Comment by DrBomb** [comment]
Most likely not. I use GetTradeConfirmations plenty on a live website and has not failed me once

**Comment by ThreadShakur** [comment]
Maybe problem in time witch i give to function? Can you give me part of code where you call GetTradeConfirmations please?

**Comment by ThreadShakur** [comment]
Ok problem was in tag.... tag must be conf... guys.. your lib is really amasing< but you should make documentation...
