### ISSUE TITLE
I got error with login

### ISSUE THREAD

**Issue by ThreadShakur** [DrBomb/python-steamcommunity#5]
File "/home/vadim/Документы/python/SteamMobileAuth.py", line 18, in generateAuthCode
    secret = b64decode(secret)
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

where i can got shared secret?

**Comment by DrBomb** [comment]
You should have googled a bit first.
Either you can grab it from an Android Phone using the method listed [here](https://github.com/SMVampire/SteamBotDev/wiki/Getting-Shared-Secret-from-Android-%28Windows%29)

Or you can set up [Steam Desktop Authenticator](https://github.com/Jessecar96/SteamDesktopAuthenticator)

**Comment by ThreadShakur** [comment]
where i can get its shared secret from Steam Desktop Authenticator

**Comment by DrBomb** [comment]
Set it up with and account, if you did it right there should be a .mafile with all the details you need.

**Comment by ThreadShakur** [comment]
well, shared secret its encryption in SDA?

**Comment by DrBomb** [comment]
It's only encrypted if you set it up to be encrypted.

**Comment by ThreadShakur** [comment]
so you don't know where in .maFile i can get its encrypted secret?

**Comment by ThreadShakur** [comment]
or it in manifest.json?

**Comment by DrBomb** [comment]
look at the .maFile, it should have a key that says shared_secret

**Comment by ThreadShakur** [comment]
in my maFile 
8wsFXkTgaq7Sl7KHL9He7ZZtk4vZsdqE8hf6YOEQhIzU9WZlYy221DzeCbmULrLKvr12j+c0hii47dY/sV4K7545UP2vU/SaS1DyOk8wGsz+QmnQ5dq/CuCGHDziQ+iih3NYvdw1oMf4aUaqJNAoLeyUzev7SegTq947LQoKgm/h4yiLM3v0qAxP9fmKZPAKVguqIp1wbMg6dAJu4RCKQX4hemuMMGyqDPW0b9Q4HCKXKshRMM92GCiiFZMldSHkCCUUc6Tb2Cc/ijzGyMDutk4mX+fb3pZLfAqs+NdINb/pcxyytjRFP914C17JhyGwMOG1kUZmLxroxDtPQitNC/UnJw9004uq6JS0i8DMFrWXhtUppDWO5XbmgsN583nXamClYmqzHsZRCzp/gUpTh5jOY/mBY3l0Dseosay7T/jBA6UnXs0WlEksJMcgKEK6HqAgOV/BnLekDciQMLUsj8OyK6TvSo/1Rt8n1whlPeM999krlS8vBUQyNHLPOL96uVKOW5bWBY3YJjqtdlIvDOHpCxxm0PFOoPTIj9FKbqlBLmH6G+u0OgIZk33OjWGde9bR7HavhHIfL3m2CtfVd5A0IeNYHxTLOQI3+/9CbZ89x8roNifBrYV7/JueFGmtUYXWihL+R0WbMBqmQMuZ/XEuinZewVoIYRucT69LHkdsxXo8Jbq0Uif0eeC1XLE6pMqEI+zV1hQon4zilgMXRwpfNjdYT7BMvuLK5+jlrB72kJlOtKF7PrCEhsvxq92Hl6AA+SOC2F+XTiX94uMoRwVYDcQzBFS6Spyi60Plz+USXg0YFtrdsLN0G7GeEeOg7kYvA4PyvMkqkOYGBdhHiBjjkDWF7AlwFQ87GfS2Fjm5lLHLA+18qlKwRPt6P9kYKRW91+Ba9+JZCYgPsYzgqLrCE/y1GlNKRJbfwxjOJXAXtj8R+/IBSh9yjZ0tjQChRc7co/h+zT+ciGDO3viJnQ9Rwlr08NeXx8kZxXAhphVM002aoOW8aQKf5U8n/migcacOeMdWL39zYe4b9/tcBtiodGeEgHT3dnxMYoRb7sde/HfMuDq/twHuhjj8CqsG

this code

**Comment by DrBomb** [comment]
Remove the authenticator from your steam account and try again, next time DO NOT PLACE AN ENCRYPTION PASSWORD

**Comment by ThreadShakur** [comment]
ok thanks for help!
