### ISSUE TITLE
What is app id in SteamInventory functions?

### ISSUE THREAD

**Issue by ThreadShakur** [DrBomb/python-steamcommunity#6]
I want to get somebody inventory, there is parameter appid, what is it? Maybe steam64?

**Comment by KowalskiThomas** [comment]
AppId is the Steam application ID.

PAYDAY 2 Steam Store link: http://store.steampowered.com/app/218620
=> PAYDAY 2 appid is 218620

**Comment by ThreadShakur** [comment]
How to get inventory of somebody with function get_inventory?

**Comment by ThreadShakur** [comment]
Ok.. how to accept trade before sending? How on Steam Desctop Autenticator?

**Comment by KowalskiThomas** [comment]
Maybe you should read the library's code before asking all those questions.
Most of the code (well, maybe not for Steam Guard) but all the code concerning trade offers, inventories and items is very clear.
