### ISSUE TITLE
Get inventory func, how to get object item in json 

### ISSUE THREAD

**Issue by ThreadShakur** [DrBomb/python-steamcommunity#9]
How to get item object from inventory.items?

**Comment by KowalskiThomas** [comment]
Inventory.items is a dictionary using the app Id and the context Id. For example, If you have loaded the trading cards and want to use the result, you'll use 
Inventory.items[753][6] and you'll have a list of items. 

Btw I'm not sure but I don't think the issues on GitHub are supposed to be used for "I don't know how to use the library questions", rather for bugs, enhancements and you know, this kind of things.

**Comment by DrBomb** [comment]
Yeah, I'd prefer you stopped asking us here how to use the library. It's still on development so if you want to use it you will have to figure it out yourself.
